-- 스태빌라이저 테이블 수정
ALTER TABLE Stabilizer
ADD COLUMN IF NOT EXISTS smoothness DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS rattle DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS build_quality DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS sound_profile DECIMAL(3,1) DEFAULT 0.0;

-- 키캡 테이블 수정
ALTER TABLE Keycap
ADD COLUMN IF NOT EXISTS thickness DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS rgb_compatible BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS durability DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS build_quality DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS sound_profile DECIMAL(3,1) DEFAULT 0.0;

-- 플레이트 테이블 수정
ALTER TABLE Plate
ADD COLUMN IF NOT EXISTS thickness DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS flex_level DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS size DECIMAL(3,1) DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS weight DECIMAL(3,1) DEFAULT 0.0;

-- 스위치 테이블 수정
ALTER TABLE Switches
ADD COLUMN IF NOT EXISTS stem_material VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS housing_material VARCHAR(50) DEFAULT 'Unknown',
ADD COLUMN IF NOT EXISTS spring_material VARCHAR(50) DEFAULT 'Unknown'; 