[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
JAVA_VERSION = "17"
SPRING_PROFILES_ACTIVE = "production" 