[build]
builder = "nixpacks"
buildCommand = "./gradlew clean bootJar -x test --no-daemon"

[deploy]
startCommand = "java -jar build/libs/klue_sever-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
JAVA_VERSION = "17"
GRADLE_OPTS = "-Dorg.gradle.daemon=false -Xmx512m" 